complete -c loc -n "__fish_use_subcommand" -s c -l profile -d 'specific profile to use' -r
complete -c loc -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c loc -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c loc -n "__fish_use_subcommand" -f -a "version" -d 'Print version info and exit'
complete -c loc -n "__fish_use_subcommand" -f -a "completion" -d 'Generate shell completion scripts for bash, zsh, fish, elvish or powershell'
complete -c loc -n "__fish_use_subcommand" -f -a "profile" -d 'Manage profile'
complete -c loc -n "__fish_use_subcommand" -f -a "login" -d 'Login Logic Operating Centre'
complete -c loc -n "__fish_use_subcommand" -f -a "logout" -d 'Logout Logic Operating Centre'
complete -c loc -n "__fish_use_subcommand" -f -a "init" -d 'Initialise CLI Workspace'
complete -c loc -n "__fish_use_subcommand" -f -a "checkout" -d 'Switch to a given project/scenario'
complete -c loc -n "__fish_use_subcommand" -f -a "project" -d 'Manage projects'
complete -c loc -n "__fish_use_subcommand" -f -a "scenario" -d 'Manage scenarios'
complete -c loc -n "__fish_use_subcommand" -f -a "trigger" -d 'Manage triggers'
complete -c loc -n "__fish_use_subcommand" -f -a "logic" -d 'Manage Logics'
complete -c loc -n "__fish_use_subcommand" -f -a "data-process" -d 'Manage data processes'
complete -c loc -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c loc -n "__fish_seen_subcommand_from version" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create profile'
complete -c loc -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "current" -d 'Show current profile'
complete -c loc -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get profile'
complete -c loc -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all profile'
complete -c loc -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "use" -d 'Switch to specific profile'
complete -c loc -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a specific profile'
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -l name -d 'Name of profile' -r
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -l server-url -d 'Server URL of Logic Operating Centre' -r
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -l description -d 'Description of profile' -r
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from current" -s v -l verbose -d 'Show more details of current profile'
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from current" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from use" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from login" -l username -d 'Username' -r
complete -c loc -n "__fish_seen_subcommand_from login" -l password -d 'Password' -r
complete -c loc -n "__fish_seen_subcommand_from login" -l password-stdin -d 'Take the password from stdin'
complete -c loc -n "__fish_seen_subcommand_from login" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from logout" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from checkout" -l reset -d 'Reset current project/scenario'
complete -c loc -n "__fish_seen_subcommand_from checkout" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "create" -d 'Create project'
complete -c loc -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "get" -d 'Get project'
complete -c loc -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "list" -d 'List all projects'
complete -c loc -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "edit" -d 'Edit given project'
complete -c loc -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "delete" -d 'Delete a given project'
complete -c loc -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "deploy" -d 'Deploy project'
complete -c loc -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "pull" -d 'Pull a project to sync server data to local'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -l unit-id -d 'Create Project in Unit' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -l name -d 'Name of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -l description -d 'Description of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -l project-name -d 'Name of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -l project-id -d 'ID of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -l remote -d 'Fetch projects from remote server'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -l project-name -d 'Name of Project that need to edit' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -l project-id -d 'ID of Project that need to edit' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -l unit-id -d 'New binding Unit of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -l name -d 'Name of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -l description -d 'Description of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -l project-name -d 'Name of Project that need to delete' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -l project-id -d 'ID of Project that need to delete' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -l remote -d 'Delete Project from remote server'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from deploy" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from pull" -l project-name -d 'Name of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from pull" -l project-id -d 'ID of Project' -r
complete -c loc -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from pull" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create scenario'
complete -c loc -n "__fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get scenario'
complete -c loc -n "__fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all scenarios'
complete -c loc -n "__fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given scenario'
complete -c loc -n "__fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given scenario'
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from create" -l name -d 'Name of Scenario' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from create" -l description -d 'Description of Scenario' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from create" -l project-name -d 'Linked Project name of Scenario' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from create" -l project-id -d 'Linked Project ID of Scenario' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from get" -l scenario-name -d 'Name of Scenario' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from get" -l scenario-id -d 'ID of Scenario' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from list" -l remote -d 'List Scenarios from LOC Server'
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from edit" -l scenario-name -d 'Name of Scenario that need to edit' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from edit" -l scenario-id -d 'ID of Scenario that need to edit' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from edit" -l name -d 'Name of Scenario' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from edit" -l description -d 'Description of Scenario' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from delete" -l scenario-name -d 'Name of Scenario that need to delete' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from delete" -l scenario-id -d 'ID of Scenario that need to delete' -r
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from delete" -l remote -d 'Delete Scenario from remote server'
complete -c loc -n "__fish_seen_subcommand_from scenario; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from subscriber" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from subscriber" -f -a "api-route" -d 'Manage API routes'
complete -c loc -n "__fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from subscriber" -f -a "scheduled-job" -d 'Manage scheduled jobs'
complete -c loc -n "__fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from subscriber" -f -a "subscriber" -d 'Manage subscribers'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create API Route'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get API Route'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all API Routes'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given API Route'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given API Route'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and __fish_seen_subcommand_from list" -l remote -d 'List API Route from LOC Server'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create scheduled job'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get scheduled job'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all scheduled jobs'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given scheduled job'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given scheduled job'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create subscriber'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get subscriber'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all subscribers'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given subscriber'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given subscriber'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create a new Logic'
complete -c loc -n "__fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "build" -d 'Build and deploy Logics'
complete -c loc -n "__fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List Logics'
complete -c loc -n "__fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit Logic'
complete -c loc -n "__fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete Logic'
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from create" -l name -d 'Name of the new Logic' -r
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from create" -l logic-type -d 'Type of the new Logic' -r
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from create" -l language -d 'Language of the new Logic' -r
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from create" -l entrypoint-file-path -d 'Entrypoint file path of the new Logic' -r -F
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from build" -s a -l all -d 'Build all logics in current workspace'
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from build" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from list" -l logic-type -d 'Type of Logic' -r
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from list" -l remote -d 'List Logics from LOC Server'
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from edit" -l name -d 'Name of the Logic to edit' -r
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from delete" -l logic-type -d 'Type of Logic' -r
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from delete" -l remote -d 'Delete Logic from LOC Server'
complete -c loc -n "__fish_seen_subcommand_from logic; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create data process'
complete -c loc -n "__fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get data process'
complete -c loc -n "__fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all data processes'
complete -c loc -n "__fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given data process'
complete -c loc -n "__fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given data process'
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from create" -l name -d 'Name of Data Process' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from create" -l description -d 'Description of Data Process' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from get" -l data-process-name -d 'Name of Data Process' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from get" -l data-process-permanent-identity -d 'Permanent Identity of Data Process' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from get" -l remote -d 'Fetch Data Processes from remote server'
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from list" -l remote -d 'Fetch Data Processes from remote server'
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from edit" -l data-process-name -d 'Name of Data Process that need to edit' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from edit" -l data-process-permanent-identity -d 'Permanent Identity of Data Process that need to edit' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from edit" -l name -d 'Name of Data Process' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from edit" -l description -d 'Description of Data Process' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from delete" -l data-process-name -d 'Name of Data Process that need to edit' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from delete" -l data-process-permanent-identity -d 'Permanent Identity of Data Process that need to edit' -r
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from delete" -l remote -d 'Delete Data Process from remote server'
complete -c loc -n "__fish_seen_subcommand_from data-process; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "version" -d 'Print version info and exit'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "completion" -d 'Generate shell completion scripts for bash, zsh, fish, elvish or powershell'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "profile" -d 'Manage profile'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "login" -d 'Login Logic Operating Centre'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "logout" -d 'Logout Logic Operating Centre'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "init" -d 'Initialise CLI Workspace'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "checkout" -d 'Switch to a given project/scenario'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "project" -d 'Manage projects'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "scenario" -d 'Manage scenarios'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "trigger" -d 'Manage triggers'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "logic" -d 'Manage Logics'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "data-process" -d 'Manage data processes'
complete -c loc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from version; and not __fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from login; and not __fish_seen_subcommand_from logout; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from checkout; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create profile'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "current" -d 'Show current profile'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get profile'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all profile'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "use" -d 'Switch to specific profile'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from current; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from use; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a specific profile'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "create" -d 'Create project'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "get" -d 'Get project'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "list" -d 'List all projects'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "edit" -d 'Edit given project'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "delete" -d 'Delete a given project'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "deploy" -d 'Deploy project'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from deploy; and not __fish_seen_subcommand_from pull" -f -a "pull" -d 'Pull a project to sync server data to local'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create scenario'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get scenario'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all scenarios'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given scenario'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from scenario; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given scenario'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from subscriber" -f -a "api-route" -d 'Manage API routes'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from subscriber" -f -a "scheduled-job" -d 'Manage scheduled jobs'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and not __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from subscriber" -f -a "subscriber" -d 'Manage subscribers'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create API Route'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get API Route'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all API Routes'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given API Route'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from api-route; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given API Route'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create scheduled job'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get scheduled job'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all scheduled jobs'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given scheduled job'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from scheduled-job; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given scheduled job'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create subscriber'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get subscriber'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all subscribers'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given subscriber'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from trigger; and __fish_seen_subcommand_from subscriber; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given subscriber'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create a new Logic'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "build" -d 'Build and deploy Logics'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List Logics'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit Logic'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from logic; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete Logic'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "create" -d 'Create data process'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "get" -d 'Get data process'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "list" -d 'List all data processes'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "edit" -d 'Edit given data process'
complete -c loc -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from data-process; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from delete" -f -a "delete" -d 'Delete a given data process'
