export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_BIN_HOME="$HOME/.local/bin"

export ZSH_CONFIG="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE="$XDG_CACHE_HOME/zsh"
export ZSH_COMPDUMP="$ZSH_CACHE/zcompdump-$ZSH_VERSION"

export ZSH_DEFAULT_PROMPT="godfather"
export THEME_GODFATHER_PROMPT_RETURN_CODE_LEFT=1

# create zsh cache if not exist
mkdir -p $ZSH_CACHE

# prepare zsh configurations
typeset -U config_files
config_files=(
  # from bash script source
  $([ -d "${HOME}/.bin" ] && ls -1 -d "${HOME}/.bin/"*.sh)

  # config
  $(ls -1 -d "$ZSH_CONFIG/config.d/"*.zsh)

  # aliases
  $(ls -1 -d "$ZSH_CONFIG/aliases.d/"*.zsh)

  # functions
  $(ls -1 -d "$ZSH_CONFIG/functions.d/"*.zsh)

  # prompt
  "$ZSH_CONFIG/prompt.d/$ZSH_DEFAULT_PROMPT.zsh"
)
# load the configuration files
for config_file in $config_files; do
  source $config_file
done

unset config_files
