name: check formant

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: editorconfig-checker/action-editorconfig-checker@v1

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --check **/*.{js,ts,md,json,yaml}
